// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Marked from "marked";

var marked = Marked();

var make = Curry.__1(marked);

export {
  marked ,
  make ,
  
}
/* marked Not a pure module */
