// Generated by ReScript, PLEASE EDIT WITH CARE


var author = "Pontus Nagy";

var name = "p1xelHer0";

var description = "woo";

var lang = "en";

var title = "p1xelHer0.com";

var twitter = "@p1xelHer0";

var github = "p1xelHer0";

export {
  author ,
  name ,
  description ,
  lang ,
  title ,
  twitter ,
  github ,
  
}
/* No side effect */
