// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Fs from "fs";
import * as Path from "path";
import * as Process from "process";
import * as Belt_Array from "bs-platform/lib/es6/belt_Array.js";
import * as GrayMatter from "gray-matter";

var directory = Path.join(Process.cwd(), "_posts");

function trimMarkdownFileEnding(fileName) {
  return fileName.replace(/\.md$/, "");
}

function getAll(param) {
  var fileNames = Fs.readdirSync(directory);
  var allPostsData = Belt_Array.map(fileNames, (function (fileName) {
          var id = trimMarkdownFileEnding(fileName);
          var fullPath = Path.join(directory, fileName);
          var fileContents = Fs.readFileSync(fullPath, "utf-8");
          var match = GrayMatter(fileContents);
          var data = match.data;
          return {
                  title: data.title,
                  date: data.date,
                  id: id,
                  body: match.content
                };
        }));
  return allPostsData.sort(function (a, b) {
              if (a.date < b.date) {
                return 1;
              } else {
                return -1;
              }
            });
}

function getIds(param) {
  var fileNames = Fs.readdirSync(directory);
  return Belt_Array.map(fileNames, trimMarkdownFileEnding);
}

export {
  directory ,
  trimMarkdownFileEnding ,
  getAll ,
  getIds ,
  
}
/* directory Not a pure module */
