// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import Link from "next/link";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function Link$1(Props) {
  var _as = Props.as;
  var _external = Props.external;
  var children = Props.children;
  var className = Props.className;
  var href = Props.href;
  var passHref = Props.passHref;
  if (Belt_Option.getWithDefault(_external, false)) {
    var tmp = {
      href: href,
      rel: "noopener noreferrer",
      target: "_blank"
    };
    if (className !== undefined) {
      tmp.className = Caml_option.valFromOption(className);
    }
    return React.createElement("a", tmp, children);
  }
  var tmp$1;
  if (Belt_Option.getWithDefault(passHref, false)) {
    tmp$1 = children;
  } else {
    var tmp$2 = {};
    if (className !== undefined) {
      tmp$2.className = Caml_option.valFromOption(className);
    }
    tmp$1 = React.createElement("a", tmp$2, children);
  }
  var tmp$3 = {
    href: href,
    children: tmp$1
  };
  if (_as !== undefined) {
    tmp$3.as = Caml_option.valFromOption(_as);
  }
  if (passHref !== undefined) {
    tmp$3.passHref = Caml_option.valFromOption(passHref);
  }
  return React.createElement(Link, tmp$3);
}

var make = Link$1;

export {
  make ,
  
}
/* react Not a pure module */
