// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as DateFns from "date-fns";

function Time(Props) {
  var dateString = Props.dateString;
  var date = DateFns.format(DateFns.parseISO(dateString), "MMM d, yyy");
  return React.createElement("time", {
              dateTime: date
            }, date);
}

var make = Time;

export {
  make ,
  
}
/* react Not a pure module */
