// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function $$default(props) {
  return React.createElement(props.Component, props.pageProps);
}

export {
  $$default ,
  $$default as default,
  
}
/* react Not a pure module */
