// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Link from "../components/Link.js";
import * as React from "react";
import * as MetaData from "../lib/MetaData.js";
import * as Pervasives from "bs-platform/lib/es6/pervasives.js";
import * as Belt_Option from "bs-platform/lib/es6/belt_Option.js";
import * as Caml_option from "bs-platform/lib/es6/caml_option.js";

function MainLayout$Header(Props) {
  var home = Props.home;
  var home$prime = Belt_Option.getWithDefault(home, false);
  return React.createElement("header", undefined, home$prime ? React.createElement(React.Fragment, undefined, React.createElement("h1", undefined, React.createElement(Link.make, {
                            children: MetaData.name,
                            href: "/"
                          }))) : React.createElement("h3", undefined, React.createElement(Link.make, {
                        children: MetaData.name,
                        href: "/"
                      })));
}

var Header = {
  make: MainLayout$Header
};

function MainLayout$Navigation(Props) {
  var home = Props.home;
  var home$prime = Belt_Option.getWithDefault(home, false);
  return React.createElement(React.Fragment, undefined, "home: " + Pervasives.string_of_bool(home$prime), React.createElement("ul", undefined, React.createElement("li", undefined, React.createElement(Link.make, {
                          external: true,
                          children: "twitter",
                          href: "https://twitter.com/" + MetaData.twitter
                        })), React.createElement("li", undefined, React.createElement(Link.make, {
                          external: true,
                          children: "github",
                          href: "https://github.com/" + MetaData.github
                        })), React.createElement("li", undefined, React.createElement(Link.make, {
                          external: true,
                          children: "rss",
                          href: "/rss.xml"
                        }))));
}

var Navigation = {
  make: MainLayout$Navigation
};

function MainLayout(Props) {
  var children = Props.children;
  var home = Props.home;
  var tmp = {};
  if (home !== undefined) {
    tmp.home = Caml_option.valFromOption(home);
  }
  var tmp$1 = {};
  if (home !== undefined) {
    tmp$1.home = Caml_option.valFromOption(home);
  }
  return React.createElement("div", undefined, React.createElement(MainLayout$Header, tmp), React.createElement(MainLayout$Navigation, tmp$1), React.createElement("main", undefined, children));
}

var make = MainLayout;

export {
  Header ,
  Navigation ,
  make ,
  
}
/* Link Not a pure module */
